### ISSUE TITLE
Error starting the watcher

### ISSUE THREAD

**Issue by BLACK4585** [ActivityWatch/aw-watcher-input#27]
Hey,
I installed the watcher like described in the README. But when I start it with `poetry run aw-watcher-input --testing`, it gives me this error:
https://paste.blck-hosting.de/upload/falcon-hawk-bat

Thanks in advance!

**Comment by ErikBjare** [comment]
Don't upload logs remotely. The link is broken anyway.

**Comment by BLACK4585** [comment]
Yep since my Server is currently down. I can upload the full log here if you want.
