### ISSUE TITLE
Where is the "dist" folder?

### ISSUE THREAD

**Issue by BLACK4585** [ActivityWatch/aw-watcher-input#30]
In your documentation and the Makefile for the visualization, you are referring to a ``dist`` folder. But there is no?

**Comment by ErikBjare** [comment]
As the README states, you have to build it from the source in the visualization directory.

**Comment by ErikBjare** [comment]
No, there are source files for the "visualization" (if you can call it that), that you "build"/compile into files that get output into the dist folder.

Read the README.
