### ISSUE TITLE
How can you connect aw-watcher-input wth activity watcher?

### ISSUE THREAD

**Issue by nck974** [ActivityWatch/aw-watcher-input#5]
Hello, how can I connect aw-watcher-input with activity watcher?
I have:
1. Cloned the project
1. Installed poerty
1. Installed the watcher from the powershell as specified in the documentation.

Which further steps should I follow?

**Comment by ErikBjare** [comment]
You should then just be able to run `aw-watcher-input` in the terminal and it'll start reporting to the ActivityWatch server. 

You should see the bucket in the 'Raw Data' tab of the web UI.

**Comment by nck974** [comment]
I tried from powershell, and it seems it is not added automatically to the path. How could I do this manually?

**Comment by ErikBjare** [comment]
Ah, you should then be able to run it with `poetry run aw-watcher-input`

**Comment by nck974** [comment]
Thanks I just tried and I get the following from the root of the folder:
```bash
poetry run .\aw-watcher-input\

  FileNotFoundError

  [WinError 2] The system cannot find the file specified

  at c:\python39\lib\subprocess.py:1420 in _execute_child
      1416│             sys.audit("subprocess.Popen", executable, args, cwd, env)
      1417│
      1418│             # Start the process
      1419│             try:
    → 1420│                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      1421│                                          # no special security
      1422│                                          None, None,
      1423│                                          int(not close_fds),
      1424│                                          creationflags,
```

**Comment by ErikBjare** [comment]
Run the command exactly as I wrote it (don't add the `.\` and `\`).

**Comment by ErikBjare** [comment]
I assume that solved the issue, let me know if you find any other issues.

Closing.
